charity_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('products.urls'), name='products-urls'),
    path('events/', include('events.urls'), name='events-urls'),
    path('our-story/', include('our_story.urls'), name='our_story-urls'),
]

events/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.Events.as_view(), name='events'),
    path('<slug:slug>/', views.event_info, name='event_info'),
    path('<slug:slug>/write_review/', views.write_review, name='write_review'),
    path('<slug:slug>/edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
    path('<slug:slug>/delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))


# Create your models here.
class Event(models.Model):
    """
    Stores a single event entry related to :model:`auth.User`.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    event_image = CloudinaryField('image', default='placeholder')
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Event: {self.title}"

    class Meta:
        ordering = ['-created_on', 'author']


class Review(models.Model):
    """
    Stores a single comment entry related
    to :model:`events.Event` and :model:`auth.User`.
    """
    post = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commenter')
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment: {self.body} by {self.author}"

    class Meta:
        ordering = ['-created_on']

events/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    """"
    A form for users to submit reviews.
    """
    class Meta:
        """
        Specify the django model and order of the fields
        """
        model = Review
        fields = ('body',)

events/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Event, Review
from .forms import ReviewForm


# Create your views here.
class Events(generic.ListView):
    """
    Returns all published events ordered by the date they were created.

    ***Context***

    ``queryset``
        All published events ordered by the date they were created.

    ***Template***
    :template: events/events.html
    """
    queryset = Event.objects.filter(status=1).order_by('-created_on')
    template_name = "events/events.html"


def event_info(request, slug):
    """
    Displays the details of a single event.
    ***Context***

        ``event``
        The event object with the given slug.

        ``reviews``
        All reviews for the event ordered by the date they were created.

    ***Template***
    :template:events/event_info.html
    """

    try:
        queryset = Event.objects.filter(status=1)
        event = get_object_or_404(queryset, slug=slug)
        reviews = event.comments.order_by('-created_on').filter(approved=True)
        return render(request, 'events/event_info.html',
                    {'event': event, 'reviews': reviews})

    except Event.DoesNotExist:
        messages.info(request, 'Event not found.')
        return redirect('events')

    except Exception as e:
        messages.error(request, f"The following error occurred: {str(e)}")
        return redirect('events')


def write_review(request, slug):
    """
    Handles the submission of a new review for an event.

    ***Context***

    ``event``
        The event object with the given slug.

    ``review_form``
        The form used to submit the review.

    ***Template***
    :template: events/event_info.html
    """

    try:
        queryset = Event.objects.all()
        event = get_object_or_404(queryset, slug=slug)
        review = event.comments.filter(approved=True)

        if request.method == "POST":
            review_form = ReviewForm(data=request.POST)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.author = request.user
                review.post = event
                review.save()
                messages.success(
                    request,
                    'Review submitted successfully and awaiting approval.'
                )
                return redirect('event_info', slug=slug)
            else:
                messages.error(
                    request,
                    'Review not submitted. Please try again.'
                )
        review_form = ReviewForm()
        return HttpResponseRedirect(reverse('event_info', args=[slug]))

    except Event.DoesNotExist:
        messages.info(request, 'Event not found.')
        return redirect('events')

    except Exception as e:
        messages.error(request, f"The following error occurred: {str(e)}")
        return redirect('events')


def edit_review(request, slug, review_id):
    """
    Handles the editing of an existing review.

    ***Context***

    ``event``
        The event object with the given slug.

    ``review``
        The review object to be edited.

    ``review_form``
        The form used to edit the review.

    ***Template***
    :template: events/event_info.html
    """

    try:
        if request.method == "POST":
            queryset = Event.objects.all()
            event = get_object_or_404(queryset, slug=slug)
            review = get_object_or_404(Review, pk=review_id)
            review_form = ReviewForm(data=request.POST, instance=review)

            if review_form.is_valid() and review.author == request.user:
                review = review_form.save(commit=False)
                review.post = event
                review.approved = False
                review.save()
                messages.success(
                    request,
                    'Successful edit of review and after approval will be displayed.'
                    )
                return redirect('event_info', slug=slug)
            else:
                messages.error(
                    request,
                    'Something went wrong. Please try to edit again.'
                )

        return HttpResponseRedirect(reverse('event_info', args=[slug]))

    except Event.DoesNotExist:
        messages.info(request, 'Event not found.')
        return redirect('events')

    except Review.DoesNotExist:
        messages.info(request, 'Review not found.')
        return redirect('event_info', slug=slug)

    except Exception as e:
        messages.error(request, f"The following error occurred: {str(e)}")
        return redirect('event_info', slug=slug)


def delete_review(request, slug, review_id):
    """
    Handles the deletion of a review.

    ***Context***

    ``event``
        The event object with the given slug.

    ``review``
        The review object to be deleted.

    ***Template***
    :template: events/event_info.html
    """

    try:
        queryset = Event.objects.filter(status=1)
        event = get_object_or_404(queryset, slug=slug)
        review = get_object_or_404(Review, pk=review_id)

        if review.author == request.user:
            review.delete()
            messages.error(request, 'Review deleted!')
        else:
            messages.info(
                request, 'You can only delete your own reviews!')

        return HttpResponseRedirect(reverse('event_info', args=[slug]))

    except Event.DoesNotExist:
        messages.error(request, 'Event not found.')
        return redirect('events')

    except Review.DoesNotExist:
        messages.error(request, 'Review not found.')
        return redirect('event_info', slug=slug)

    except Exception as e:
        messages.error(request, f"The following error occurred: {str(e)}")
        return redirect('event_info', slug=slug)

events/templates/events/event_info.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="article-title"><i>{{event.title}}</i></div>
        <div class="hero-image">
            {% if "placeholder" in event.event_image.url %}
                <img class="img-fluid" src="{% static 'images/default.jpg' %}"
                    alt="placeholder image">
            {% else %}
                <img class="img-fluid" src=" {{ event.event_image.url }}"
                    alt="{{ event.title }}">
            {% endif %}
        </div>
    <div class="article-content my-4">
        {{event.content | safe}}
    </div>
    <div class="comments-section m-4 p-4 bg-light">
        <p class="fs-3 mb-4">Reviews</p>
        {% if user.is_authenticated %}
        <a href="#" id="write-review" class="text-decoration-none" aria-label="click to add review">
            <span class="p-2 bg-dark-subtle">
                <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2"/>
                </svg> Review
            </span>
        </a>
        {% else %}
        <p>Please <a href="{% url 'account_login' %}" aria-label="login">login</a> to leave a review.</p>
        {% endif %}
        {% for review in reviews %}
        <div class="posted-comments mt-4">
            <div class="comment">
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                        <path d="M2.678 11.894a1 1 0 0 1 .287.801 11 11 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8 8 0 0 0 8 14c3.996 0 7-2.807 7-6s-3.004-6-7-6-7 2.808-7 6c0 1.468.617 2.83 1.678 3.894m-.493 3.905a22 22 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a10 10 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9 9 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105"/>
                    </svg> from <strong>{{review.author}}</strong>: <i id="{{review.id}}">{{review.body | safe}}</i>
                </span>
                {% if user.is_authenticated and review.author == request.user %}
                    <span><button class="btn btn-light edit-comment-button" data-review_id="{{ review.id }}" aria-label="Edit">Edit</button></span>
                    <span><button class="btn btn-light delete-comment-button" data-review_id="{{ review.id }}" aria-label="Delete">Delete</button></span>
                {% endif %}
                <hr>
            </div> 
        </div>
        {% endfor %}
    </div>
</div>

<!--Modal for editing or adding comment-->
<div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="reviewModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title fs-5" id="exampleModalLabel">Review</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="reviewForm" method="post">
                    {{ review_form | crispy }}
                    {% csrf_token %}
                    <textarea id="id_body_modal" name="body" class="textarea form-control" rows="5" required></textarea>
                    <button id="submitButton" type="submit"
                    class="btn btn-secondary mt-3" aria-label="Publish">Publish</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!--Modal to confirm deletion -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Attention!</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Please confirm you want to delete your comment. </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="#" class="btn btn-primary" id="deleteConfirm" aria-label="Delete">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block forJS %}
<script src="{% static 'js/reviews.js' %}"></script>
{% endblock %}

events/templates/events/events.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<h2 class="text-center mt-5 mb-0 pb-0 py-4 animate__animated animate__fadeInDown"><i>Upcoming Events</i></h2>
    
<div class="container my-4">
    <div class="row g-4">
        {% for event in event_list %}
        <div class="col-md-6 col-lg-4 animate__animated animate__fadeInDown animate__slower">
            <div class="card event">
                {% if "placeholder" in event.event_image.url %}
                <img class="card-img-top img-thumbnail" src="{% static 'images/default.jpg' %}"
                    alt="placeholder image">
                {% else %}
                <img class="card-img-top img-thumbnail" src=" {{ event.event_image.url }}"
                    alt="{{ event.title }}">
                {% endif %}
                <div class="card-body">
                    <p class="card-title fs-5">{{event.title}}</p>
                    <p class="card-text">{{event.excerpt}}</p>
                    <a href="{% url 'event_info' event.slug %}" class="btn view-info" aria-label="View Event">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}