charity_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('products.urls'), name='products-urls'),
    path('events/', include('events.urls'), name='events-urls'),
    path('our-story/', include('our_story.urls'), name='our_story-urls'),
]

events/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.Events.as_view(), name='events'),
    path('<slug:slug>/', views.event_info, name='event_info'),
    path('<slug:slug>/write_review/', views.write_review, name='write_review'),
    path('<slug:slug>/edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
    path('<slug:slug>/delete_review/<int:review_id>/', views.delete_review, name='delete_review'),
]

products/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.Products.as_view(), name='products'),
    path("<slug:slug>/view_product/", views.view_product, name="view-product"),
    path('favorites/', views.favorites, name='favorites'),
    path(
        'add_to_favorites/<int:product_id>/',
        views.add_to_favorites, name='add_to_favorites'),
    path(
        'favorites/remove_favorite/<int:favorite_id>',
        views.remove_favorite, name='remove_favorite'),
    path('basket/', views.basket, name='basket'),
    path(
        'basket/remove_item/<int:basket_id>',
        views.remove_item, name='remove_item'),
    path('after_payment/', views.after_payment, name='after_payment'),
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Awaiting Approval"), (1, "Approved"))
CONDITION = ((0, "New"), (1, "Used"), (2, "Refurbished"))


# Create your models here.
class Product(models.Model):
    """
    Stores a single product entry related to :model:`auth.User`.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='product_posts')
    product_image = CloudinaryField('image', default='placeholder')
    description = models.TextField()
    condition = models.IntegerField(choices=CONDITION, default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=1)
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Product: {self.title} "

    class Meta:
        ordering = ['-created_on', 'author']


class Basket(models.Model):
    """
    Stores a single basket entry related to :model:`auth.User`
    and :model:`products.Product`.
    """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='buyer')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='product')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField(default=1)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Basket: {self.product} | added by {self.user}"

    class Meta:
        ordering = ['-created_on', 'user']


class Favorite(models.Model):
    """
    Stores a single favorite entry related to :model:`auth.User`
    and :model:`products.Product`.
    """
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='favorited_by')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='favorite_product')
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.product.title}"

products/forms.py
from django import forms
from .models import Basket


class BasketForm(forms.ModelForm):
    """
    A form for users to add items to their basket.
    """
    class Meta:
        """
        Specify the django model and fields to be displayed.
        """
        model = Basket
        fields = ('quantity', )

products/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib import messages
from django.views import generic
from django.conf import settings
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from .models import Product, Basket, Favorite
from .forms import BasketForm

# Create your views here.


class Products(generic.ListView):
    """
    Displays a list of approved products.

    ***Context***

    ``queryset``
        The queryset of approved products.

    ***Template***
    :template: products/products.html
    """

    queryset = Product.objects.filter(status=1)
    template_name = "products/products.html"


def view_product(request, slug):
    """
    Displays the details of a single product and
    handles adding the product to the basket.

    ***Context***

    ``product``
        The product object with the given slug.

    ``basket_items``
        The basket items for the product.

    ``basket_form``
        The form for adding the product to the basket.

    ***Template***
    :template: products/view_product.html
    """

    try:
        queryset = Product.objects.filter(status=1)
        product = get_object_or_404(queryset, slug=slug)
        basket_items = Basket.objects.filter(product=product)

        if request.method == 'POST':
            basket_form = BasketForm(data=request.POST)
            if basket_form.is_valid():
                order_quantity = basket_form.cleaned_data['quantity']
                # Check if product is already in the user's basket
                existing_basket_item = Basket.objects.filter(
                    product=product, user=request.user).first()

                if existing_basket_item:
                    # Increase the quantity of the existing item
                    existing_basket_item.quantity += order_quantity
                    existing_basket_item.save()
                    messages.success(
                        request, f'The quantity of {product.title} has been '
                        f'updated in your basket!')
                else:
                    # Add a new item to the basket
                    order = basket_form.save(commit=False)
                    order.user = request.user
                    order.product = product
                    order.amount = product.price
                    order.save()
                    messages.success(
                        request, f'{product.title} added successfully '
                        f'to your basket!')

                return redirect('basket')
            else:
                messages.error(
                    request, 'There was an error adding the product to '
                    f'Your basket. Please try again.')

        basket_form = BasketForm()

        return render(
            request,
            'products/view_product.html',
            {
                'product': product, 'basket_items': basket_items,
                'basket_form': basket_form, },
            )
    except Exception as e:
        messages.error(request, f'The following error occurred:\n{str(e)}.')
        return render(request, '500.html', status=500)


def home(request):
    """
    Displays the home page.

    ***Template***
    :template: products/index.html
    """

    return render(request, 'products/index.html',)


@login_required
def basket(request):
    """
    Displays the user's basket with items and the total amount.

    ***Context***

    ``items``
        The basket items for the user.

    ``total``
        The total amount of the basket items.

    ***Template***
    :template: products/basket.html
    """

    try:
        items = Basket.objects.filter(user=request.user)
        total = sum(item.amount*item.quantity for item in items)

        context = {
            'items': items,
            'total': total,
            'paypal_client_id': settings.PAYPAL_CLIENT_ID,
        }

        return render(request, 'products/basket.html', context)

    except Exception as e:
        messages.error(request, f'The following error occurred:\n{str(e)}.')
        return render(request, '500.html', status=500)


@login_required
def remove_item(request, basket_id):
    """
    Removes an item from the user's basket.
    """

    try:
        basket_item = get_object_or_404(
            Basket, id=basket_id, user=request.user)
        basket_item.delete()
        messages.add_message(
            request, messages.ERROR, 'Item removed from your basket!')

        return HttpResponseRedirect(reverse('basket'))
    except Exception as e:
        messages.error(
            request, f'Failed to remove item because of the following '
            f'error:\n{str(e)}')
        return redirect('basket')


def after_payment(request):
    """
    Clears the user's basket after payment and
    displays the after payment page.

    ***Template***
    :template: products/after_payment.html
    """

    try:
        basket_items = Basket.objects.filter(user=request.user)
        basket_items.delete()
        messages.success(
            request, 'Payment processed successfully. Your basket has been '
            f'cleared.')

        return render(
            request,
            'products/after_payment.html',
        )
    except Exception as e:
        messages.error(
            request, f'Payment processing failed because of the following '
            f'error:\n{str(e)}')
        return render(request, '500.html', status=500)


@login_required
def add_to_favorites(request, product_id):
    """
    Adds a product to the user's favorites.
    """

    try:
        product = get_object_or_404(Product, id=product_id)
        favorite, created = Favorite.objects.get_or_create(
            user=request.user, product=product)

        if created:
            messages.success(
                request, f'{product.title} has been added to your favorites.')
        else:
            messages.info(
                request,
                f'{product.title} is already in your favorites.')

        return redirect('products')

    except IntegrityError:
        messages.error(request, 'Database error. Please try again.')
        return redirect('products')

    except Exception as e:
        messages.error(
            request, f'The following unexpected error occurred:\n{str(e)}')
        return redirect('products')


@login_required
def favorites(request):
    """
    Displays the user's favorite products.
    ***Context***

    ``favorites``
        The favorite products for the user.

    ***Template***
    :template: products/favorites.html
    """

    try:
        favorites = Favorite.objects.filter(user=request.user)

        return render(
            request,
            'products/favorites.html',
            {'favorites': favorites, },
            )

    except Exception as e:
        messages.error(
            request, f'The following unexpected error occurred:\n{str(e)}')
        return render(request, '500.html', status=500)


@login_required
def remove_favorite(request, favorite_id):
    """
    Removes a product from the user's favorites.
    """

    try:
        favorite = get_object_or_404(
            Favorite, id=favorite_id, user=request.user)
        favorite.delete()
        messages.error(request, 'Item removed from favorites!')
        return HttpResponseRedirect(reverse('favorites'))

    except Exception as e:
        messages.error(
            request, f'Failed to remove item because of the following '
            f'error:\n{str(e)}')
        return redirect('favorites')

products/templates/products/after_payment.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<div class="container-fluid home-div">
    <div class="row text-center">
        <div class="col col-md-12">
            <h3 class="animate__animated animate__fadeInUp animate__slow"><i>Thanks for your payment</i></h3>
            <span>
            <a href="{% url 'products' %}" class="btn view-info m-4 animate__animated animate__fadeInUp animate__delay-2s" aria_label="View more products">View more products</a>
            <a href="{% url 'events' %}" class="btn view-info m-4 animate__animated animate__fadeInUp animate__delay-2s" aria_label="View our events">View our Events</a>
            </span>
        </div>
    </div>
</div>

{% endblock content %}

products/templates/products/basket.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<!-- Basket Overview Section -->
<h2 class="text-center mt-5 mb-0 pb-0 py-4 animate__animated animate__fadeInDown animate__slow"><i>Your Basket</i></h2>

<div class="container-fluid">
    <div class="row mx-4 my-4">
        <div class="col col-md-12 animate__animated animate__fadeInUp animate__slow">
            <table class="table table-hover table-striped table-responsive">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ item.product.title }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" fill="currentColor" class="bi bi-currency-euro" viewBox="0 0 16 16">
                                <path d="M4 9.42h1.063C5.4 12.323 7.317 14 10.34 14c.622 0 1.167-.068 1.659-.185v-1.3c-.484.119-1.045.17-1.659.17-2.1 0-3.455-1.198-3.775-3.264h4.017v-.928H6.497v-.936q-.002-.165.008-.329h4.078v-.927H6.618c.388-1.898 1.719-2.985 3.723-2.985.614 0 1.175.05 1.659.177V2.194A6.6 6.6 0 0 0 10.341 2c-2.928 0-4.82 1.569-5.244 4.3H4v.928h1.01v1.265H4v.928z"/>
                            </svg> {{ item.amount }}
                        </td>
                        <td>
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" fill="currentColor" class="bi bi-currency-euro" viewBox="0 0 16 16">
                                <path d="M4 9.42h1.063C5.4 12.323 7.317 14 10.34 14c.622 0 1.167-.068 1.659-.185v-1.3c-.484.119-1.045.17-1.659.17-2.1 0-3.455-1.198-3.775-3.264h4.017v-.928H6.497v-.936q-.002-.165.008-.329h4.078v-.927H6.618c.388-1.898 1.719-2.985 3.723-2.985.614 0 1.175.05 1.659.177V2.194A6.6 6.6 0 0 0 10.341 2c-2.928 0-4.82 1.569-5.244 4.3H4v.928h1.01v1.265H4v.928z"/>
                            </svg> {% widthratio item.quantity 1 item.amount %}
                        </td>
                        <td class="text-center">
                            <button type="submit" class="btn btn-danger btn-sm btn-to-remove-item fs-6"
                            data-basket_id='{{item.id}}' aria-label="Remove"><strong>-</strong></button>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3" class="text-end"><strong>Total Amount</strong></td>
                        <td>
                            <strong>
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" fill="currentColor" class="bi bi-currency-euro" viewBox="0 0 16 16">
                                    <path d="M4 9.42h1.063C5.4 12.323 7.317 14 10.34 14c.622 0 1.167-.068 1.659-.185v-1.3c-.484.119-1.045.17-1.659.17-2.1 0-3.455-1.198-3.775-3.264h4.017v-.928H6.497v-.936q-.002-.165.008-.329h4.078v-.927H6.618c.388-1.898 1.719-2.985 3.723-2.985.614 0 1.175.05 1.659.177V2.194A6.6 6.6 0 0 0 10.341 2c-2.928 0-4.82 1.569-5.244 4.3H4v.928h1.01v1.265H4v.928z"/>
                                </svg> {{ total }}
                            </strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div><a href="{% url 'products' %}" id="continue-shop" class="btn btn-secondary mb-3" aria-label="Continue Shoping">Continue Shopping</a></div>
            <div class=paypal-button-parent>
                <div id="paypal-button-container" data-total="{{ total }}" data-paypal-client-id="{{ paypal_client_id }}">
            </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal to confirm removal of product-->
{% for item in items %}
<div class="modal fade" id="removalModal" tabindex="-1" aria-labelledby="removalModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title fs-5">{{item.product.title}}</p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Please confirm you want to remove the above item. </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
                <a href="#" class="btn btn-primary" id="removeConfirm" aria-label="Remove">Remove</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

{% block forJS %}
<script src="{% static 'js/basket.js' %}"></script>
{% endblock %}

products/templates/products/favorites.html
{% extends "base.html" %}

{% block content %}

{% load static %}


<h2 class="text-center mt-5 mb-0 pb-0 py-4 animate__animated animate__fadeInDown animate__slow"><i>Your Favorite Products</i></h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-5">
            <div class="row">
                {% for favorite in favorites %}
                <div class="card mx-auto p-2 my-4 animate__animated animate__fadeInDown animate__slow" style="width: 18rem;">
                    {% if "placeholder" in favorite.product.product_image.url %}
                    <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                        alt="placeholder image">
                    {% else %}
                    <img class="card-img-top" src=" {{ favorite.product.product_image.url }}"
                        alt="{{ product.title }}">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-title fs-5">{{favorite.product.title}}</p>
                        <p class="card-text"><svg xmlns="http://www.w3.org/2000/svg" width="1em" fill="currentColor" class="bi bi-currency-euro" viewBox="0 0 16 16">
                            <path d="M4 9.42h1.063C5.4 12.323 7.317 14 10.34 14c.622 0 1.167-.068 1.659-.185v-1.3c-.484.119-1.045.17-1.659.17-2.1 0-3.455-1.198-3.775-3.264h4.017v-.928H6.497v-.936q-.002-.165.008-.329h4.078v-.927H6.618c.388-1.898 1.719-2.985 3.723-2.985.614 0 1.175.05 1.659.177V2.194A6.6 6.6 0 0 0 10.341 2c-2.928 0-4.82 1.569-5.244 4.3H4v.928h1.01v1.265H4v.928z"/>
                        </svg> {{favorite.product.price}}</p>
                        <span class="d-flex justify-content-between">
                        <a href="{% url 'view-product' favorite.product.slug %}" class="btn btn-primary view-info" aria-label="View product">View</a>
                        <button type="submit" class="btn btn-danger btn-to-remove-favorite"
                        data-favorite_id='{{favorite.id}}' aria-label="Remove">Remove</button>
                        </span>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<!-- Modal to confirm removal of product-->
{% for favorite in favorites %}
<div class="modal fade" id="favoriteRemovalModal" tabindex="-1" aria-labelledby="FavoriteRemovalModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title fs-5">{{favorite.product.title}}</p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Please confirm you want to remove the above item. </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
                <a href="#" class="btn btn-primary" id="removeFavoriteConfirm" aria-label="Rempve item">Remove</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

{% block forJS %}
<script src="{% static 'js/favorites.js' %}"></script>
{% endblock %}

products/templates/products/index.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="container-fluid home-div mt-5">
    <div class="row home-row text-center">
        <div class="col-lg-6 col-md-12">
            <img src="{% static 'images/icononly_transparent_nobuffer.png' %}" class="animate__animated animate__fadeInUp animate__delay-1s" width="200" height="200" alt="Charity Treasures Logo">
            <h2 class="my-2 animate__animated animate__fadeInUp animate__delay-2s">
                Every Purchase, A Heartbeat of Hope!
            </h2>
            <h3>
                <a class="{% if user.is_authenticated %}d-none{% endif %} text-decoration-none animate__animated animate__fadeInUp animate__delay-2s" href="{% url 'account_signup' %}">Sign up</a>
                <span class="{% if user.is_authenticated %}d-none{% endif %} animate__animated animate__fadeInUp animate__delay-2s"> and </span> 
                <span class="animate__animated animate__fadeInUp animate__delay-2s"> Donate today to help</span> 
                <a class="text-decoration-none animate__animated animate__fadeInUp animate__delay-2s" href="{% url 'our_story' %}">our cause</a>
            </h3>
        </div>
    </div>
</div>

{% endblock %}

products/templates/products/products.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<h2 class="text-center mt-5 mb-0 pb-0 py-4 animate__animated animate__fadeInDown animate__slow"><i>Our Products</i></h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-5">
            <div class="row">
                {% for product in product_list %}
                <div class="card mx-auto p-2 my-4 animate__animated animate__fadeInDown animate__slow" style="width: 18rem;">
                    {% if "placeholder" in product.product_image.url %}
                    <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                        alt="placeholder image">
                    {% else %}
                    <img class="card-img-top" src=" {{ product.product_image.url }}"
                        alt="{{ product.title }}">
                    {% endif %}
                    <div class="card-body">
                        <p class="card-title fs-5">{{product.title}}</p>
                        <p class="card-text"><svg xmlns="http://www.w3.org/2000/svg" width="1em" fill="currentColor" class="bi bi-currency-euro" viewBox="0 0 16 16">
                            <path d="M4 9.42h1.063C5.4 12.323 7.317 14 10.34 14c.622 0 1.167-.068 1.659-.185v-1.3c-.484.119-1.045.17-1.659.17-2.1 0-3.455-1.198-3.775-3.264h4.017v-.928H6.497v-.936q-.002-.165.008-.329h4.078v-.927H6.618c.388-1.898 1.719-2.985 3.723-2.985.614 0 1.175.05 1.659.177V2.194A6.6 6.6 0 0 0 10.341 2c-2.928 0-4.82 1.569-5.244 4.3H4v.928h1.01v1.265H4v.928z"/>
                        </svg> {{product.price}}</p>
                        <span class="d-flex justify-content-between text-center">
                        <a href="{% url 'view-product' product.slug %}" class="btn view-info" aria-label="View product">View</a>
                        {% if user.is_authenticated %}
                            <form action="{% url 'add_to_favorites' product.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn view-info" aria-label="Add to Favourites">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1.5rem" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                                    </svg>
                                </button>
                            </form>
                        {% endif %}
                        </span>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

products/templates/products/view_product.html
{% extends "base.html" %}

{% block content %}

{% load static %}
{% load crispy_forms_tags %}

<h2 class="text-center mt-5 mb-0 pb-0 py-4 animate__animated animate__fadeInDown"><i>{{product.title}}</i></h2>

<div class="container-fluid text-center">
    <div class="row row-cols-md-2">
        <div class="container my-4 d-flex justify-content-center justify-content-md-end">
            <div class="row g-4">
                <div class="col col-sm-12 animate__animated animate__fadeInDown animate__slower">
                    <div class="card p-4" style="width: 20rem;">
                        {% if "placeholder" in product.product_image.url %}
                        <img class="card-img-top img-fluid" src="{% static 'images/default.jpg' %}"
                            alt="placeholder image">
                        {% else %}
                        <img class="card-img-top img-fluid" src=" {{ product.product_image.url }}"
                            alt="{{ product.title }}">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="container my-4 d-flex justify-content-center justify-content-md-start">
            <div class="row g-4">
                <div class="col col-sm-12 animate__animated animate__fadeInDown animate__slower">
                    <div class="card p-4" style="width: 20rem;">
                        {{product.description | safe}}
                        <div class="card-body">
                            <p class="card-text"><svg xmlns="http://www.w3.org/2000/svg" width="1em" fill="currentColor" class="bi bi-currency-euro" viewBox="0 0 16 16">
                                <path d="M4 9.42h1.063C5.4 12.323 7.317 14 10.34 14c.622 0 1.167-.068 1.659-.185v-1.3c-.484.119-1.045.17-1.659.17-2.1 0-3.455-1.198-3.775-3.264h4.017v-.928H6.497v-.936q-.002-.165.008-.329h4.078v-.927H6.618c.388-1.898 1.719-2.985 3.723-2.985.614 0 1.175.05 1.659.177V2.194A6.6 6.6 0 0 0 10.341 2c-2.928 0-4.82 1.569-5.244 4.3H4v.928h1.01v1.265H4v.928z"/>
                            </svg> {{product.price}}</p>
                            {% if user.is_authenticated %}
                                <form id=basket_form method='post'>
                                    {% csrf_token %}
                                    <label for="id_quantity">Quantity:</label>
                                    <input type="number" id="id_quantity" name="quantity" min="1" value="1" required>
                                    <button type="submit" class="btn view-info m-4" aria-label="Add to basket">Add to Basket</button>
                                </form>
                                <form action="{% url 'add_to_favorites' product.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn view-info" aria-label="Add to favorites">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="1.5rem" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143q.09.083.176.171a3 3 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15"/>
                                        </svg>
                                    </button>
                                </form>
                            {% else %}
                                <p>Please <a href="{% url 'account_login' %}">Login</a> to add the item to your basket</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}